import React from 'react';
import { Bill, PersonShareSummary, DiningCompanion } from '@/types';
import { formatCurrency } from '@/lib/utils';

interface PrintableReceiptProps {
  bill: Bill;
  personShares: PersonShareSummary[];
  payer: DiningCompanion | null;
  paidStatus: Record<string, boolean>;
}

export const PrintableReceipt: React.FC<PrintableReceiptProps> = ({
  bill,
  personShares,
  payer,
  paidStatus,
}) => {
  return (
    <div className="hidden print:block font-mono text-black p-8 max-w-2xl mx-auto bg-white text-xs">
      {/* Header */}
      <div className="text-center pb-4 border-b-2 border-dashed border-black">
        <h1 className="text-xl font-black uppercase tracking-wider mb-1">
          {bill.restaurantName}
        </h1>
        {bill.address && <p className="text-xs mb-0.5">{bill.address}</p>}
        <p className="text-xs">
          {bill.dateTime} {bill.billNumber ? `• ${bill.billNumber}` : ''}
        </p>
        <p className="text-xs font-bold mt-1">
          SPLIT THE BILL SUMMARY
        </p>
      </div>

      {/* Bill Totals Summary */}
      <div className="py-4 border-b border-black text-xs space-y-1">
        <div className="flex justify-between font-bold">
          <span>Items Subtotal:</span>
          <span>{formatCurrency(bill.subtotal)}</span>
        </div>
        {bill.tax > 0 && (
          <div className="flex justify-between">
            <span>GST / Tax ({bill.taxRate}%):</span>
            <span>{formatCurrency(bill.tax)}</span>
          </div>
        )}
        {bill.serviceCharge > 0 && (
          <div className="flex justify-between">
            <span>Service Charge ({bill.serviceChargeRate}%):</span>
            <span>{formatCurrency(bill.serviceCharge)}</span>
          </div>
        )}
        <div className="flex justify-between font-black text-sm pt-2 border-t border-dashed border-black">
          <span>RECEIPT GRAND TOTAL:</span>
          <span>{formatCurrency(bill.grandTotal)}</span>
        </div>
        <div className="text-[11px] pt-1">
          <span>Original receipt paid by: <strong>{payer?.name || 'Organizer'}</strong></span>
        </div>
      </div>

      {/* Diners Split Matrix */}
      <div className="py-4 border-b-2 border-dashed border-black">
        <h2 className="font-bold text-xs uppercase tracking-wider mb-3">
          INDIVIDUAL DINER SHARES ({personShares.length} MEMBERS)
        </h2>

        <div className="space-y-4">
          {personShares.map((s, idx) => (
            <div key={s.person.id} className="border border-black p-3 rounded">
              <div className="flex justify-between items-center font-bold text-xs pb-1 border-b border-black">
                <span>
                  {idx + 1}. {s.person.name}
                  {s.person.isOrganizer ? ' (Organizer)' : ''}
                  {s.person.id === payer?.id ? ' (Payer)' : ''}
                </span>
                <span className="font-black text-sm">
                  {formatCurrency(s.totalShare)} ({paidStatus[s.person.id] ? 'PAID' : 'PENDING'})
                </span>
              </div>

              {/* Items */}
              <div className="pt-2 space-y-1 text-[11px]">
                {s.items.map((it) => (
                  <div key={it.item.id} className="flex justify-between">
                    <span>
                      • {it.item.name} {it.isShared ? `(1/${it.assignedCount} share)` : '(Solo)'}
                    </span>
                    <span>{formatCurrency(it.shareAmount)}</span>
                  </div>
                ))}
                {(s.taxShare > 0 || s.serviceChargeShare > 0) && (
                  <div className="flex justify-between text-gray-700 pt-1 border-t border-dotted border-gray-400">
                    <span>+ Tax & Service share:</span>
                    <span>{formatCurrency(s.taxShare + s.serviceChargeShare)}</span>
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Footer */}
      <div className="text-center pt-4 text-[10px] space-y-1">
        <p className="font-bold">ALL SHARES RECONCILED WITH 100% ARITHMETIC ACCURACY</p>
        <p>Generated by Split The Bill • Easy Restaurant Expense Splitting</p>
      </div>
    </div>
  );
};
